version: "3.8"
services:

  # postgres:
  #   image: postgres:16-alpine3.17
  #   container_name: local_pgdb
  #   restart: always
  #   ports:
  #     - '${POSTGRES_PORT}:5432'
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - local_pgdata:/var/lib/postgresql/data
  #   networks:
  #     - hk-network

  # pgadmin:
  #   image: dpage/pgadmin4:8.6
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - '${PGADMIN_PORT}:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres
  #   networks:
  #     - hk-network

  # redis:
  #   image: redis:7.2.4-alpine3.19
  #   container_name: tcel-smr-redis01
  #   restart: always
  #   ports:
  #     - '${REDIS_PORT}:6379'
  #   expose:
  #     - 6379
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - hk-network
  
  # srs:
  #   image: ossrs/srs:5
  #   ports:
  #     - '${SRS_RTMP_LIVESTREAM_SERVER_PORT}:1935'
  #     - '${SRS_HTTP_API_SERVER_PORT}:1985'
  #     - '${SRS_HTTP_LIVESTREAM_SERVER_PORT}:8080'
  #   restart: unless-stopped
  #   networks:
  #     - hk-network

  srs_master:
    image: ossrs/srs:latest
    container_name: srs_master
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    volumes:
      - ./srs_master.conf:/usr/local/srs/conf/srs.conf

  srs_slave:
    image: ossrs/srs:latest
    container_name: srs_slave
    ports:
      - "1936:1935"
      - "1986:1985"
      - "8081:8080"
    volumes:
      - ./srs_slave.conf:/usr/local/srs/conf/srs.conf

volumes:
  local_pgdata:
  pgadmin-data:
  redis_data:

networks:
  hk-network:
    external: true
